version: '3'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: nodesafio
    networks:
      - olarmundo
    depends_on:
      mydatabase:
        condition: service_healthy
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules  # Prevents overwriting of the container's node_modules

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      node:
        condition: service_healthy
    networks:
      - olarmundo

  mydatabase:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mydatabase
    command: --innodb-use-native-aio=0
    tty: true
    restart: always
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    networks:
      - olarmundo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 8

networks:
  olarmundo:
    driver: bridge
  
